### ISSUE TITLE
Consolidate data sources

### ISSUE THREAD

**Issue by Lei-Gu** [Lei-Gu/CoronaVirus#11]
- consolidate the master folder for all datasets (cases, gdp, population)

- cosolidate timeseries coronavirus data sources
   1. for chart use
   2. for mapping use

**Comment by arthurcw** [comment]
1. Merged John Hopkins (non-US) and New York Times (US) dataset for consistent spatial scale ("Covid19_YYYYMMDD.csv" in Dataset folder)
2. Included confirmed cases and deaths count
3. Available in country, state/province and county/city (label as Admin2) levels;
   - e.g. for the US,
            data row 15448: # of cases in the US is 85618 on 3/26/20
            data row 15382  # of cases in Wyoming is 56 on 3/26/20
            data row 14047 # of cases in Teton, WY is 8 on 3/26/20
   - when load to javascript, use filter to select appropriate level of data (e.g. country level data has empty value for "Admin2" and "Province_State" fields.)
