### ISSUE TITLE
Geo mapping

### ISSUE THREAD

**Issue by Lei-Gu** [Lei-Gu/CoronaVirus#15]
Confirmed Cases:  global , County(Zoomed in)

Death Cases: global , County(Zoomed in)

**Comment by arthurcw** [comment]
current issue
1. needs another extension for  master cluster to work with LayerGroup
2. marker cluster doesn't aggregate by geographical boundaries

**Comment by arthurcw** [comment]
Completed. If have time, add toggle switch to show death data
